[package]
name = "py32f031-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core", "critical-section"] }
cortex-m-rt = "0.7.5"
cortex-m-semihosting = "0.5"
defmt = "1.1"
defmt-rtt = "1.2"
embassy-executor = { version = "0.10", features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-sync = { version = "0.8", features = ["defmt"] }
embassy-time = { version = "0.5", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embedded-io = "0.7"
embedded-io-async = "0.7"
heapless = "0.9"
panic-halt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }
portable-atomic = { version = "1", features = ["critical-section"] }
py32-hal = { version = "0.4.1", path = "../..", features = ["time-driver-tim1", "py32f031c18"] }
