#!/usr/bin/env python3
"""
update_cargo_mcu_features.py

Description:
  This script automatically synchronizes the MCU feature flags in `py32-hal/Cargo.toml`
  with the supported chips defined in `py32-metapac/Cargo.toml`.
  It reads the `py32-metapac` configuration, extracts all chip names, and replaces
  everything under the `# --- MCU selection ---` section in `py32-hal/Cargo.toml`.

Usage:
  Run this script from the `py32-hal` directory, passing the path to the `py32-metapac` directory.
  
  Example:
      cd py32-hal
      python3 scripts/update_cargo_mcu_features.py ../py32-data/build/py32-metapac

Custom Rules:
  You can modify the `rules` list in this script to automatically inject additional Cargo
  features (like USB support) for specific MCU series using regular expressions.
"""

import argparse
import os
import re

# Regex rule configuration mapping pattern -> list of extra features
# Example: matching py32f07* series to enable musb?/builtin-py32f07x
RULES = [
    (re.compile(r"^py32f07"), ['"musb?/builtin-py32f07x"']),
]

def main():
    parser = argparse.ArgumentParser(description="Update MCU selection in Cargo.toml based on py32-metapac")
    parser.add_argument("metapac_path", help="Path to py32-metapac directory")
    args = parser.parse_args()

    metapac_cargo = os.path.join(args.metapac_path, "Cargo.toml")
    if not os.path.exists(metapac_cargo):
        print(f"Error: {metapac_cargo} not found")
        return

    # Extract chips from py32-metapac Cargo.toml
    chips = []
    with open(metapac_cargo, "r", encoding="utf-8") as f:
        in_features = False
        for line in f:
            line = line.strip()
            if line.startswith("[features]"):
                in_features = True
                continue
            if line.startswith("[") and in_features:
                break
            # Features typically look like `py32f030x6 = []`
            if in_features and line.startswith("py32"):
                chip = line.split("=")[0].strip()
                chips.append(chip)
                
    chips.sort()

    if not chips:
        print("Error: No chips found in py32-metapac/Cargo.toml")
        return



    # Generate the new MCU selection section
    lines = [
        "# --- MCU selection ---\n",
        "# DO NOT EDIT MANUALLY. This section is automatically generated by `scripts/update_cargo_mcu_features.py`.\n"
    ]
    for chip in chips:
        deps = [f'"py32-metapac/{chip}"']
        for pattern, extra_features in RULES:
            if pattern.match(chip):
                deps.extend(extra_features)
        
        lines.append(f"{chip} = [{', '.join(deps)}]\n")
        
    # Now update py32-hal/Cargo.toml
    # Ensure this script works regardless of where it is run, 
    # assuming it is in `scripts/` directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    hal_cargo = os.path.join(script_dir, "..", "Cargo.toml")
    
    if not os.path.exists(hal_cargo):
        print(f"Error: {hal_cargo} not found.")
        return

    with open(hal_cargo, "r", encoding="utf-8") as f:
        content = f.read()
        
    # Replace everything after "# --- MCU selection ---"
    marker = "# --- MCU selection ---"
    parts = content.split(marker)
    if len(parts) != 2:
        print(f"Error: Could not find exactly one '{marker}' in Cargo.toml")
        return
        
    new_content = parts[0] + "".join(lines)
    
    with open(hal_cargo, "w", encoding="utf-8") as f:
        f.write(new_content)
        
    print(f"Successfully updated {len(chips)} MCUs in py32-hal/Cargo.toml")

if __name__ == "__main__":
    main()
