name: CI build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "*.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use nightly Rust
        # lock to 2024-08-23 and wait for embassy-executor to be updated
        run: |
          rustup default nightly
          rustup component add rust-src
          rustup target add thumbv6m-none-eabi
      - name: Build Only
        run: cargo build --features py32f030k28,rt,embassy --target thumbv6m-none-eabi
